### ISSUE TITLE
pandas format (as default one day)

### ISSUE THREAD

**Issue by sergiolucero** [cnavarreteliz/datachile-api#1]
Most of the time, right after pulling data as the result of a query, most people will create a pandas.DataFrame. Couldn't we provide an option (df=True) as openaq does? It saves a lot of time AND points people to the direction of pandas, which would encourage plotting, quick transition to DBs, excel, etc.

**Comment by cnavarreteliz** [comment]
`pd.DataFrame(query1)` should work fine.
