### ISSUE TITLE
can´t install datachile package because of dependence with "mondrian_rest" package

### ISSUE THREAD

**Issue by kailkuhn** [cnavarreteliz/datachile-api#2]
Cannot install because of this dependency. I also did not manage to install the mondrian package. can you please help me with that in order to be able to acces the API? Thank you so much!

**Comment by cnavarreteliz** [comment]
@kailkuhn Can you paste your log?

**Comment by cnavarreteliz** [comment]
For install mondrian_rest, you must run in your terminal 
`pip3 install git+https://github.com/Datawheel/py-mondrian-rest.git#egg=mondrian_rest-0.1`
