### ISSUE TITLE
mondrian_rest trouble

### ISSUE THREAD

**Issue by sergiolucero** [cnavarreteliz/datachile-api#3]
pip install datachile fails:

Collecting mondrian_rest==0.1 (from datachile)
  Could not find a version that satisfies the requirement mondrian_rest==0.1 (from datachile) (from versions: )
No matching distribution found for mondrian_rest==0.1 (from datachile)

**Comment by cnavarreteliz** [comment]
Solved vía [7dc8ff4](https://github.com/datachile/datachile-python-client/commit/7dc8ff410048e5dcd12580ae638bc3a174cae262)
