### ISSUE TITLE
Mondrian problem when installing datachile thru pip

### ISSUE THREAD

**Issue by kailkuhn** [cnavarreteliz/datachile-api#4]
I keep getting this error when trying to install:

  Could not find a version that satisfies the requirement mondrian_rest==0.1 (from datachile) (from versions: )
No matching distribution found for mondrian_rest==0.1 (from datachile)

can anyone help?

**Comment by cnavarreteliz** [comment]
@kailkuhn  Are you using 0.0.6 version?

**Comment by sergiolucero** [comment]
Yes we are, Carlos, and it still doesn't work. Full output:

    pip install datachile

Collecting datachile
  Using cached https://files.pythonhosted.org/packages/97/bb/67aeaab4fa0812813444194a84549a271136a1df9d8c4280e279f186937d/datachile-0.0.6.tar.gz
Collecting mondrian_rest==0.1 (from datachile)
  Could not find a version that satisfies the requirement mondrian_rest==0.1 (from datachile) (from versions: )
No matching distribution found for mondrian_rest==0.1 (from datachile)

**Comment by sergiolucero** [comment]
it seems that tests on the developers' machines, if they exist, are passing but datachile does NOT install on our machines.

**Comment by cnavarreteliz** [comment]
Now should be ok @sergiolucero @kailkuhn 

I uploaded mondrian-rest to pip and `datachile v0.0.7` uses `mondrian-rest`

**Comment by sebacea** [comment]
Installing mondrian-rest and then datachile 0.0.6 works but importing ChileCube from datachile shows `ModuleNotFoundError: No module named 'mondrian_rest'`
Installing datachile 0.0.7 instead shows `  File "/Users/sebacea/anaconda3/lib/python3.6/site-packages/datachile/__init__.py", line 1
    from mondrian-rest import Cube, MondrianClient
                 ^
SyntaxError: invalid syntax`

Finally, datachile 0.0.8 shows the same error as version 0.0.6`

**Comment by tomcastro** [comment]
Bumping this, I'm getting an error saying urllib does not exist, so it cannot install mondrian-rest. Also, if I install mondrian_rest with no dependencies (as urllib is included with Python 3.6), I get the same error as @sebacea (invalid syntax).

**Comment by sergiolucero** [comment]
I tried just now, pip tries to retrieve version 0.0.8 and fails on account of urlparse.

**Comment by cnavarreteliz** [comment]
https://github.com/datachile/datachile-python-client/blob/master/datachile/chilecube.py

I fixed that in `v.0.0.9`. I hope that you can use `datachile` without problems @sergiolucero @tomcastro @sebacea .
Tell me more about if this error is persistent in new version. Thanks!

**Comment by sergiolucero** [comment]
Have you pushed to pypi? I'm getting version 0.0.8

**Comment by sebacea** [comment]
Same question as @sergiolucero, i'm not able to retrieve version 0.0.9

Collecting datachile==0.0.9
  Could not find a version that satisfies the requirement datachile==0.0.9 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8)
No matching distribution found for datachile==0.0.9

**Comment by cnavarreteliz** [comment]
Tested and working!

**Comment by sebacea** [comment]
I'm still getting the error 

> Traceback (most recent call last):
>   File "/Users/sebacea/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   File "<ipython-input-7-4c5e4bc96182>", line 1, in <module>
>     from datachile import ChileCube
> 
>   File "/Users/sebacea/anaconda3/lib/python3.6/site-packages/datachile/__init__.py", line 1
>     from mondrian-rest import Cube, MondrianClient
>                  ^
> SyntaxError: invalid syntax
