### ISSUE TITLE
ConnectionError. I think that API_BASE is wrong

### ISSUE THREAD

**Issue by aoguedao** [cnavarreteliz/datachile-api#6]
Hi! Today I tried to use this api client, but it got the following error with the example code: 

```
from datachile import ChileCube

client = ChileCube()
query = client.get_cubes()

print(query)
```

`ConnectionError: HTTPSConnectionPool(host='chilecube.datawheel.us', port=443): Max retries exceeded with url: /cubes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58b0d8c7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

I think that API_BASE in datachile/chilecube.py is wrong.  Actually it is `API_BASE = "https://chilecube.datawheel.us"`, but in datachile api webpage (https://es.datachile.io/about/api) the url base is https://chilecube.datachile.io

My setup: 
Ubuntu 18.04 LTS with conda environment (python 3.7).

PD: Sorry for my english, it isn't my primary language.

**Comment by cnavarreteliz** [comment]
@aLoNsolml can you try updating the library? :) I just updated the `API_BASE`

**Comment by aoguedao** [comment]
> @aLoNsolml can you try updating the library? :) I just updated the `API_BASE`

Hi! It works! 

Gracias Carlos!
